# Generated by Django 3.0.6 on 2020-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=128, verbose_name='')),
                ('toptext', models.CharField(blank=True, max_length=128, verbose_name='Text top')),
                ('bottomtext', models.CharField(blank=True, max_length=128, verbose_name='Text bottom')),
            ],
        ),
    ]
